on:
  push:
    branches:
      - main

name: Deploy React Cosmos (@sys42/ui)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/init-pnpm

      - name: Build React Cosmos
        run: pnpm --filter @sys42/ui run cosmos-export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/ui/cosmos-export
