on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-copilot

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs['packages/copilot--release_created']}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config-copilot.json
          manifest-file: .release-please-manifest-copilot.json

  publish-copilot:
    if: ${{needs.release-please.outputs.release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/init-pnpm

      - name: Publish 🚀
        shell: bash
        run: pnpm publish packages/copilot --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
